import os

ACCESS_TOKEN = os.environ['ACCESS_TOKEN']
VERIFY_TOKEN = os.environ['VERIFY_TOKEN']
IMGUR_ACESS_TOKEN = os.environ['IMGUR_ACESS_TOKEN']
IMGUR_REFRESH_TOKEN = os.environ['IMGUR_REFRESH_TOKEN']
IMGUR_CLIENT_ID = os.environ['IMGUR_CLIENT_ID']
IMGUR_CLIENT_SECRET = os.environ['IMGUR_CLIENT_SECRET']
