# Generated by Django 2.1.2 on 2018-11-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagrammer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('genre', models.TextField(default='無')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'instagrammer',
            },
        ),
    ]
