# Generated by Django 2.1.2 on 2018-11-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammer',
            name='picture',
            field=models.ImageField(default='', upload_to='profile_pics/'),
        ),
    ]
