# Generated by Django 2.1.2 on 2018-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igbot', '0004_auto_20181121_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
