# Generated by Django 2.1.2 on 2019-01-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igbot', '0005_instagrammer_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_lived_user_access_token', models.TextField(default='')),
                ('long_lived_user_access_token', models.TextField(default='')),
                ('page_access_token', models.TextField(default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
