# Generated by Django 2.1.2 on 2018-11-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igbot', '0002_instagrammer_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrammer',
            name='picture',
        ),
        migrations.AddField(
            model_name='instagrammer',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
