# Generated by Django 2.1.2 on 2018-11-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igbot', '0003_auto_20181121_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammer',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='instagrammer',
            name='genre',
            field=models.TextField(default=''),
        ),
    ]
